<?php

/**
 * @file
 * fmf_market module.
 */

/**
 * Implements hook_node_view
 *
 * concat address fields to a single line for GMAP
 */
function fmf_market_node_view($node, $view_mode, $langcode) {

    $node_wrapper = entity_metadata_wrapper('node', $node);

    $addr = $node_wrapper->field_street->value() . ' ' . $node_wrapper->field_city->value() . ', ' . $node_wrapper->field_state->value() . ' ' . $node_wrapper->field_zip->value();

    $node_wrapper->field_one_line_address->set($addr);
    $node_wrapper->save();

}

/**
 * Implements hook_node_update().
 */
function fmf_node_update() {

}


